[package]
name = "jonathan_converter"
version = "1.0.0"
edition = "2018"
description = "Converts the graphics and text resources of the classic adventure game 'Jonathan' to regular PNG and text files"
authors = ["Malte Thiesen <malte@kamalook.de>"]

[dependencies]
clap = "2.33.0"
failure = "0.1.7"
pcx = "0.2"
png = "0.16.1"
rayon = "1.3.0"
